# Generated by Django 3.0 on 2020-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('User_name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Emial', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=20)),
                ('Latitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=100, null=True)),
                ('Catagory', models.CharField(max_length=100)),
                ('Base_cost', models.FloatField()),
                ('Date_created', models.DateField(auto_now_add=True)),
                ('Date_closing', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('User_name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Emial', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=20)),
                ('Latitude', models.CharField(max_length=20)),
            ],
        ),
    ]
