# Generated by Django 3.0 on 2020-09-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0002_auto_20200914_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='Total_number_of_biders',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.FloatField()),
                ('Notes', models.TextField(max_length=1000)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='Bid.Bid')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='Bid.Client')),
            ],
        ),
    ]
