# Generated by Django 3.0 on 2020-09-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bid', '0003_auto_20200915_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bid_id',
            new_name='Bid_id',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='client_id',
            new_name='Client_id',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='offered_price',
            new_name='Offered_price',
        ),
    ]
